name: DeathSwap
version: 1.1.0
author: Bram2323
main: me.bram2323.DeathSwap.Main
discription: This is a deathswap plugin for 1.15+!
api-version: 1.15
website: www.spigotmc.org/resources/2-player-death-swap-1-15-1-16.79176/

commands:
  dssettings:
   description: Change a setting
   usage: /dssettings <set,get,help>
  dsstart:
   description: Force start the game
   usage: /dsstart
  dsstop:
   description: Force stop the game
   usage: /dsstop
  dsinfo:
   description: Some info about the plugin
   usage: /dsinfo
  dsready:
   description: Toggles if your ready or not
   usage: /dsready [get,start]
  dskill:
   description: Kill yourself ingame
   usage: /dskill
  dstp:
   description: Opens a menu to teleport to other players when spectating
   usage: /dstp <player>
  dsstats:
   description: Shows the stats of a player
   usage: /dsstats <player>